CREATE TABLE User (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 firstName VARCHAR(255) NULL,
 lastName VARCHAR(255) NULL,
 password_hash CHAR(60) NOT NULL,
 dateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 dateUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 );
