CREATE TABLE Record (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dateTimeCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    pulse TEXT,
    pulseTypeID INT UNSIGNED,
    FOREIGN KEY (pulseTypeID) REFERENCES PulseType(id)
);
